@echo off
set SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxuem5oYndna3VzZ2RjbXZnem5mIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NjMzNjE4NywiZXhwIjoyMDkxOTEyMTg3fQ.NmiG1w_Fps6MRGeYkjijDVwwPReVyiiaeurUM7NOhO8
python bulk_create_users.py users_template.csv
pause
