-- ===================================================================
-- Sewadar reconciliation SQL (generated by validate-sewadars.mjs)
--   newly_added  : INSERTs sewaders in the sheet but not in DB (ALL columns)
--   changed      : UPDATEs changed fields from the sheet
--   draft_remove : DELETE sewadars whose sheet Form_Status is "Draft"
-- NOTE: records in DB but NOT in the sheet are deliberately LEFT as-is (no DELETE).
-- Run these in the Supabase SQL editor. Review first; use in a transaction.
-- ===================================================================

-- UPDATE changed fields (sheet value wins) --
